In [1]:
import numpy as np


In [7]:
npa = np.array([0,'Kunal'])

In [8]:
npa

array(['0', 'Kunal'], dtype='<U11')

In [9]:
a = np.arange(10)

In [10]:
np.max(a)

9

# Useful functions

In [11]:
np.arange(10)

# is used to create continuous elements starting from 0 and till the specified number

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#to create arrays containing only zeros, 
#shape is given as arguments
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [16]:
#same goes for ones

In [17]:
#to create identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
#to create an array consisting of even spaced numbers in the given interval
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

## Random


In [22]:
np.random.rand(4)

array([0.96367835, 0.97163523, 0.24748349, 0.57243355])

In [23]:
np.random.randn(2)

array([ 0.22587226, -0.38479922])

In [24]:
np.random.uniform(5)

2.084300527046002

In [25]:
np.random.randint(1,10)

2

## Max Min Argmax Argmin

### Argmax and Argmin are used to get the index of the maximum or the minimum values

In [27]:
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [28]:
np.max(a)

14

In [29]:
np.min(a)

0

In [30]:
np.argmin(a)

0

In [31]:
np.argmax(a)

14

# Array Operations

In [32]:
x = np.arange(10)

In [33]:
x + x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
x * x

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [36]:
x ** 4

array([   0,    1,   16,   81,  256,  625, 1296, 2401, 4096, 6561],
      dtype=int32)

### Universal Array Functions

In [37]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [38]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [39]:
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [40]:
np.log(x)

C:\Users\KARAN S07\Anaconda3\envs\myDjangoEnv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [41]:
np.cos(x)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

### Statistics

#### mean:
Average of the array
#### max:
Maximum element in the array
#### std:
Standard deviation of the array
#### var:
Variance of the array
#### sum:
Sum of the array

In [45]:
x.mean(),x.max(),x.std(),x.var(),x.sum()

(4.5, 9, 2.8722813232690143, 8.25, 45)